### ISSUE TITLE
필라이즈 체크리스트

### ISSUE THREAD

**Issue by zena-1106** [BoostSwiftUI/SwiftUI#6]
# 필라이즈 체크리스트
#### 헤더
- [ ] 로고 넣기
- [ ] 아이콘 넣기
- [ ] 캘린더 영역잡기

#### Contents set
- [ ] 내 식단 점수 확인하기 영역 모두 구현(버튼 필수)
- [ ] 스크롤 구현

### 추가
- [ ] 내 식단 점수 확인하기 영역 모두 구현(버튼 필수)
- [ ] 검색 UI 구현
- [ ] 상단탭 -'동작 1 - 메뉴' 터치 구현
- [ ] 리스트 구현
- [ ] 스크롤 구현

### 추가완료
- [ ] 로띠 추가
- [ ] 버튼 상태 변경

#### 헤더
- [ ] 캘린더 UI구현
- [ ] 아래 컨텐츠 UI 구현

### 추가
- [ ] 상단탭 -'동작 2 - list영역 스와이프' 터치 구현
- [ ] 즐겨찾기, 직접등록 페이지 UI 구현 (플레이스홀더 이미지 구현)

**Comment by jeongju9216** [comment]
피그마로 체크리스트 관리를 진행하기 때문에 이슈를 close 합니다.
